### ISSUE TITLE
Reply-to email addresses should match sender of email

### ISSUE THREAD

**Issue by jesperronn** [svalgaard/fskintra#12]
Just an idea so that I can reply directly to emails sent by Fskintra: Reply-to email address should be the real email address of the email sender. If for instance I get an email written by "thomas", I can reply directly to the email to the mail address registered by thomas in the Intra app.

I am just noting this as an idea, will not do anything in code right now  (unfortunately)

**Comment by svalgaard** [comment]
Efter lang betænkningstid (4+ år) tænker jeg at det ikke er en god idé at bruge reply-to i e-mail fra fskintra. Det er ikke helt usandsynligt at et autosvar eller andet ender tilbage til en afsender, der slet ikke er klar over, hvad der sker.  :)
