### ISSUE TITLE
Send email with 'address book' of class (list of parents)

### ISSUE THREAD

**Issue by jesperronn** [svalgaard/fskintra#13]
Just an idea. I would love to have an email with all contact info of all parents in the class. Names, phone numbers, emails. Awesome if I can use Fskintra script to send me an email everytime somebody updates contact info. 

I am just registering this as an idea, since I am not certain of how to build it into the script.

**Comment by BennySLBS** [comment]
Hi, I have made a standalone tool for getting contact info from website to .vcf files (and I have imported it into Gmail adress book.
See further here: http://slbs.dk/skfi-adr.html (in dainish, the code is missing, but available - just ask me)

**Comment by jesperronn** [comment]
@svalgaard nice work in 871e528 :+1: 

På sigt kunne det være cool at kombinere de to og vedhæfte `.vcf` vcards med oplysningerne...men det kræver lidt flere overvejelser af hvad man skulle sætte ind i filen

**Comment by bennyslbs** [comment]
@jesperronn Det bliver vist bare at lade sig inspirere af mit, for det er lavet i perl, men det kunne jeg godt have interesse i at kombinere. Mit tool virker ikke længere, for der er ændret i listerne siden jeg lavede det.
