### ISSUE TITLE
Ugeplaner are never re-sent even if content is updated

### ISSUE THREAD

**Issue by jesperronn** [svalgaard/fskintra#14]
For our school, suddently the week plans are never updated again. I can see the content is updated in the web client. Unfortunately I get no new email.

It seems there is a check in [hasBeenSent()](https://github.com/svalgaard/fskintra/blob/master/skoleintra/semail.py#L197), which always returns true for week plans. 

My guess is that the headers that is sent on a week plan somehow changed, so that there is no last-modified date. I took a brief look in the network panel, and here is a copy of the response headers:

request:
```
GET /Infoweb/Fi/VisUgeplan.asp?Plan=1&Uge=201503 HTTP/1.1
```

response:
```
HTTP/1.1 200 OK
Date: Tue, 13 Jan 2015 19:41:07 GMT
Server: Microsoft-IIS/6.0
P3P: CP=%93NOI DSP COR NID ADMa OUR NOR STA%94
X-Powered-By: ASP.NET
Content-Length: 16063
Content-Type: text/html
Cache-control: private
```
How about other users? Are you also experiencing this problem?

**Comment by jesperronn** [comment]
In case this is general, we may be able to consider freshness anyway. Unfortunately there is no content telling when the week plan was updated.

An alternative could be to md5hash the content of the emails. If changed, then send again. Suggestions, comments?

**Comment by svalgaard** [comment]
Måske cacher vi for meget af tidligere versioner. Giver nyeste version af dev branchen resultater?
Vi bruger ikke selv ugeplaner, så jeg kan ikke selv teste det.

**Comment by jesperronn** [comment]
@svalgaard har lige prøvet med dev branchen commit 188ff22. Det virker :+1: 

nu kører scriptet og sender mig de gamle ugeplaner som har været ændret siden første udsendelse. 

Den kan du godt merge :)
