### ISSUE TITLE
Get list of lektier(home work) and make it available in different forms

### ISSUE THREAD

**Issue by bennyslbs** [svalgaard/fskintra#16]
I am working on a new feature: Get the home work (lektier) from each child and make it awailable in smarter forms:
- SMS to each child with the homework for tomorrow
  Our childs often spends time at the school after school time and wants to make their homework there.
- Website (via org-mode)
- Optional create calender entries with home work (could be accessed offline at school to limit number of SMSs and to have the homework for next days available)

The work is performed at https://github.com/bennyslbs/fskintra/tree/lektier.

**Comment by svalgaard** [comment]
Det ser rigtigt spændende ud. Vores skole bruge ikke lektiemodulet, men for de skoler, hvor det bliver brugt vil det være superfint at have med.
Melder du tilbage, når det når en tilstand, hvor du synes at det kan lægges ind sammen med resten?

**Comment by bennyslbs** [comment]
Jeg siger til når jeg gerne vil have det med.
Jeg har pt. ikke lavet noget der skriver til config filen, men læser en del information derfra, som man selv må skrive i config filen.
Lektierne er jeg i gang med at lægge i en database (sqlite3) - håber at det er ok. Jeg har valgt det, da jeg synes at det virker smartere til de små informationsmængder + det kan være lettere at lave en standalone viewer (f. eks. en infoskærm som også skal vise andre ting). - Håber at det er i orden.

**Comment by bennyslbs** [comment]
Det er måske tid til at få det med i master branchen.
Status er:
- Afsendelse af lektie email og SMS har været i drift i et stykke tid
- Lektier bliver gemt i en database (blev kørt i test før sommerferien, men tilrettet
  efterfølgende, så der kan være issues her)
- Lektie Web er lige lavet
- begrænset test indtil det nye skoleår er igang

Plads til forbedringer:
- Opdatering af config filen foregår manuelt, men er dokumenteret i README.md
  Jeg synes at jeg kan forsvare det, for man kan fint bruge det uden lektie-delen,
  så det skulle ikke ødelægge noget for nogen.

web-delen:
Jeg har lavet en folder, weblib med webLektier.py som tilgår databasen og genererer html output.
Den bruger ikke noget af det andet i fskintra (udover config hvis den køres som standalone (test).

Derudover har jeg lavet en www folder, som er tiltænkt at kopiere til en webserver - kalder webLektier.py, så der er minimal funktionalitet (import + kald).
Læs mere om dette i README.md.

Sig til hvis jeg skal lave et pull-request.

**Comment by bennyslbs** [comment]
Nu har jeg fået Lektie Web finpudset og fixet lidt efter der er kommet lektier igen.
Der er et eksempel (uden rigtige data) her: http://slbs.dk/skfi/lektieweb_ex.html

Det kører for børnenes skole for alle klasser, og kan fint bruges nu. Der kan dog godt komme flere fixes når flere begynder at bruge det.

Jeg har merget master ind på min 'lektier' branch.
Skal jeg merge branchen ind på master, og hvis ja med eller uden fast forward, eller vil du hellere vente lidt?

**Comment by svalgaard** [comment]
Hej Benny

Vi må hellere få det lagt dine ændringer ind hos mig, så der er ét sted med det hele.

Jeg kunne dog godt tænke mig at rette en anelse inden det kommer ind i min master, herunder tænker jeg især at der nok er en del der ikke kommer til at bruge SMS delen, dvs. måske vil det være smartere at dele README.md op, så sms delen kommer over i en anden fil, så bliver mere overskuelig?

Kunne vi evt. lave et standard-filnavn for databasen, så man ikke behøver at angive dette?

Kan lektieID'et for hvert barn ikke findes automatisk?

Vores skole bruger ikke lektiemodulet, dvs. jeg kan ikke rigtigt se, om det faktisk virker... Men det gør det sikkert. :)

**Comment by svalgaard** [comment]
Merge du det bare ind i din "master" gerne med fastforward, og lave en pull-request til mig. Så vil jeg se, om jeg kan få kigget på det i løbet af den næste uges tid.

**Comment by bennyslbs** [comment]
Hej Jens

## Opsplining af README.md

Opsplitning af readme er helt fint med mig. Hvis du gør det kan du ved samme lejlighed rette hvis der er noget der er for knudret, eller skal jeg nok gøre det.


## Default Lektie database filnavn

Standardfilnavn for databasen kunne vel være at default er (CONFIG_FN er aktuel config fil):
1: configfilename med .txt erstattet af .lektier.db: os.path.splitext(CONFIG_FN)[0] + '.lektier.db'
eller
2: dir(configfilename)/lektier.db: print os.path.splitext("~/abc/def.ghi.jkl")[0] + '.lektier.db'

Nr. 2 har nok den fordel at hvis der er flere forældre der kører fskintra, bruger de den samme database, så det hælder jeg til. Så slipper jeg også for at lave om i kommentarer til web-delen.

Det vil næppe gå godt med lektier fra 2 skoler i een lektie database.


## lektieids

Hvis ikke lektieids er sat i konfig-filen, er lektiemodulet disablet.

Hvis man vil bruge lektie-delen skal man lave opsættning af sms-grupper og/eller opsætning af web-del (symlinkning t. web server) eller anden læseadgang til databasen.

For klasser hvor man selv har børn, kan man godt automatisk finde ID'erne (men har ikke kigget på det).

For andre klasser på en skole må man gætte sig frem (mere eller mindre fortløbende på vores skole).
Det bruger jeg i følge aftale med skolen som en service til hele skolen.

## Merge
Jeg venter lige en par dage. Pt. kræver sms- grupper at der er en SMS GW, selvom sms-grupperne kun bruges til at sende emails, det laver jeg lige lidt om på.

**Comment by svalgaard** [comment]
Eftersom din kode er til det "gamle design", mine børns skole ikke bruger lektie-modulet i forældreintra og hele ForældreIntra nok lukker ned til sommer, lukker jeg sagen for nu. Genåbn hvis det bliver aktuelt. :)
