### ISSUE TITLE
Encoding problem I kontaktadresse delen

### ISSUE THREAD

**Issue by kjeldahl** [svalgaard/fskintra#20]
Jeg får følgende fejl. 

igger efter nye adresser
raceback (most recent call last):
 File "fskintra/fskintra.py", line 18, in <
dule>
   skoleintra.pgContactLists.skoleContactLists()
 File "fskintra/skoleintra/pgContact
sts.py", line 60, in skoleContactLists
   bs = surllib.skoleGetURL(URL_MAIN, True, False, True)
 File "fskintra/skoleintra/surllib.p
, line 185, in skoleGetURL
   if os.path.isfile(lfn) and not noCache and not config.S
P_CACHE:
 File "/opt/lib/python2.5/posixpath.py", line 208, in isfi
 
   st = os.stat(path)
nicodeEncodeError: 'ascii' codec can't encode character u'
xc6' in position 115: ordinal not in range(128)

**Comment by jesperronn** [comment]
Ser du kører med python 2.5. Jeg kører 2.7, men får en lignende fejl blot på beskedoversigten

**Comment by svalgaard** [comment]
Jeg vil tro at det skyldes at I begge har børn med danske tegn i navnet?
Det burde være nemt at fixe (uden at børnene skifter navn)... Jeg vil se, om jeg kan få kigget på det senere i dag...

**Comment by jesperronn** [comment]
Ja vores efternavn indeholder i hvert fald `ø`

**Comment by kjeldahl** [comment]
Ingen af mine børn har danske tegn i deres navne hverken fornavn eller efternavn.
Jeg har desværre ikke selv lige tid til at kigge nærmere på det i dag.

**Comment by svalgaard** [comment]
Kan jeg få jer til at prøve nyeste udgave af dev-branchen og melde tilbage om det hjælper?

**Comment by kjeldahl** [comment]
Samme fejl, men et af mine børn får faktisk et æ i navnet inde på siden.
```
Vælger [Lauge SPÆ]
skoleGetURL: Trying to fetch http://www.skovbyskolen.skoleintra.dk/Infoweb/Fi2/OpdaterLogfil.asp?Id=1323&Checksum=569a8a029661a4c0c14fb472751fcce1 child=Axel Kjeldahl 3A
Kigger efter nye adresser
skoleGetURL: Trying to fetch http://www.skovbyskolen.skoleintra.dk/Infoweb/Fi/Klasselister.asp child=Lauge SPÆ
Traceback (most recent call last):
  File "./fskintra/fskintra.py", line 18, in <module>
    skoleintra.pgContactLists.skoleContactLists()
  File "fskintra/skoleintra/pgContactLists.py", line 91, in skoleContactLists
    listsCheckList(postData, opt['value'])
  File "fskintra/skoleintra/pgContactLists.py", line 29, in listsCheckList
    bs = surllib.skoleGetURL(URL_MAIN, True, False, True, postData)
  File "fskintra/skoleintra/surllib.py", line 184, in skoleGetURL
    postData = urllib.urlencode(postData)
  File "/opt/lib/python2.5/urllib.py", line 1262, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc6' in position 2: ordinal not in range(128)
```

**Comment by kjeldahl** [comment]
Jeg får stadig fejl ved hentning af klasselister på dev branch:
```
skoleGetURL: Henter fra cache http://www.skovbyskolen.skoleintra.dk/Infoweb/Fi/Klasselister.asp
Traceback (most recent call last):
  File "./fskintra/fskintra.py", line 18, in <module>
    skoleintra.pgContactLists.skoleContactLists()
  File "/share/HDA_DATA/jacob/fskintra/skoleintra/pgContactLists.py", line 60, in skoleContactLists
    bs = surllib.skoleGetURL(URL_MAIN, True, False, True)
  File "/share/HDA_DATA/jacob/fskintra/skoleintra/surllib.py", line 208, in skoleGetURL
    config.log('skoleGetURL: %s' % unienc(lfn), 2)
  File "/share/HDA_DATA/jacob/fskintra/skoleintra/config.py", line 96, in log
    sys.stderr.write(u'%s\n' % s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128)```

**Comment by svalgaard** [comment]
Hmmm - det virker hos mig, men jeg tror jeg kan se, hvad der måske kan løse problemet. Jeg kigger lige...

**Comment by svalgaard** [comment]
Jeg lukker sagen igen; meld tilbage, hvis det mod forventning ikke virker.
