### ISSUE TITLE
UnicodeEncodeError - når køres fra crontab på RPi.

### ISSUE THREAD

**Issue by bennyslbs** [svalgaard/fskintra#24]
Når jeg kører fskintra fra crontab på en Raspberry Pi får jeg en UnicodeEncodeError (se nedenfor) (og har gjort det længe).

Jeg ser ikke problemet hvis jeg kører fskintra.py fra en shell.
Er det kun mig der har problemet? ... og er der evt. en der kan give et hint til opsætning af RPi'en. Jeg har prøvet om det er noget LOCALE der skal sættes op, men uden held.

Mit fix er, snuppet fra http://stackoverflow.com/questions/2276200/changing-default-encoding-of-python:
git diff
diff --git a/skoleintra/config.py b/skoleintra/config.py
index 61a9529..3d0bc5a 100644
--- a/skoleintra/config.py
+++ b/skoleintra/config.py
@@ -3,7 +3,6 @@
 #
 
 import os
-import sys
 import ConfigParser
 import codecs
 import locale
@@ -12,6 +11,10 @@ import optparse
 import time
 import re
 
+import sys
+reload(sys)  # Reload does the trick!
+sys.setdefaultencoding('UTF8')
+
 ROOT = os.path.expanduser('~/.skoleintra/')
 DEFAULT_FN = os.path.join(os.path.dirname(__file__), 'default.inf')
 CONFIG_FN = '~/.skoleintra/skoleintra.txt'

Fejl i mailen cron sender til mig:
Traceback (most recent call last):
  File "/home/benny/git/github.com/bennyslbs/fskintra/fskintra.py", line 16, in <module>
    cnames = skoleintra.schildren.skoleGetChildren()
  File "/home/benny/git/github.com/bennyslbs/fskintra/skoleintra/schildren.py", line 22, in skoleGetChildren
    config.log(u'Henter liste af børn')
  File "/home/benny/git/github.com/bennyslbs/fskintra/skoleintra/config.py", line 96, in log
    sys.stderr.write('%s\n' % s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 17: ordinal not in range(128)

**Comment by svalgaard** [comment]
Hej Benny.
Har du prøvet at skrive ```PYTHONIOENCODING=UTF-8```
i linjen før din rigtige crontab linje? Det burde løse problemet?
Jeg bruger dog selv flg. hvorved der slet ikke udskrives loglinjer der ikke kan konverteres til UTF-8 / manf får kun emails med indhold eller en email, hvis der er sket en fejl.

```
PYTHONIOENCODING=UTF-8
59 19 * * *  /stil/til/fskintra.py -q
```

**Comment by bennyslbs** [comment]
Tak, det var det der skulle til ... burde det tilføjes til README?

**Comment by svalgaard** [comment]
Det står allerede i README... :)
https://github.com/svalgaard/fskintra#cron-job
