### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ylzhou** [svalgaard/fskintra#31]
Hvad går galt? 
Jeg har også prøvet at køre uden cache, men ingen succes. 

Henter liste af børn
skoleGetURL: Trying to fetch http://www.haervejsskolen.dk/Infoweb/Fi2/Faneblade.asp child=
Login
Login på skoleintra
skoleLogin: URL https://www.haervejsskolen.dk/Infoweb/Fi2/Login.asp
skoleLogin: Brugernavn yonzho
Vælger [Minrui 3B]
skoleGetURL: Trying to fetch http://www.haervejsskolen.dk/Infoweb/Fi2/OpdaterLogfil.asp?Id=958&Checksum=445a73c002486084ba2b5342357b441c child=
Kigger efter nye adresser
skoleGetURL: Henter fra cache http://www.haervejsskolen.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /Users/yzhou/.skoleintra/cache/http/www.haervejsskolen.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Minrui 3B
skoleGetURL: Henter fra cache http://www.haervejsskolen.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /Users/yzhou/.skoleintra/cache/http/www.haervejsskolen.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Minrui 3BfKlasse=03B&fSortering=V1&fSkjult=ON&B1=Vis+liste&R1=V5
Hopper tidligere sendt besked over: <semail.Message type='contactList' date='14-06-2016' title=u'Kontaktoplysninger i 3B'>
skoleGetURL: Henter fra cache http://www.haervejsskolen.dk/Infoweb/Fi/Klasselister.asp
skoleGetURL: /Users/yzhou/.skoleintra/cache/http/www.haervejsskolen.dk/Infoweb/Fi/Klasselister.asp&CHILDNAME=Minrui 3BfKlasse=03B&fSortering=V1&fSkjult=ON&B1=Vis+liste&R1=V6
Hopper tidligere sendt besked over: <semail.Message type='contactList' date='14-06-2016' title=u'For\xe6ldrenes e-mailadresser i 3B'>
Behandler forsiden
skoleGetURL: Trying to fetch http://www.haervejsskolen.dk/Infoweb/Fi2/Forside.asp child=Minrui 3B
Traceback (most recent call last):
  File "./fskintra.py", line 19, in <module>
    skoleintra.pgFrontpage.skoleFrontpage()
  File "/Users/yzhou/bin/fskintra/skoleintra/pgFrontpage.py", line 216, in skoleFrontpage
    g[-1][1].append(itag)
IndexError: list index out of range

**Comment by svalgaard** [comment]
Hej.

Kan jeg få dig til at prøve igen med nyeste version af dev branchen og se om fejlen er gået væk?
Dvs.: git pull og dernæst git checkout dev

Hvis det ikke virker, må du meget gerne sende mig (via email) indholdet af af din forside URL. Hvis du kører fskintra med -v skriver den, hvor den ligger den hentede fil med fejl, som du dernæst kan sende mig.

**Comment by svalgaard** [comment]
Med helt nyeste version af dev branchen burde problemet være løst, da vi nu "ignorerer" hvis der mangler en titel. Åbn gerne sagen igen, hvis det ikke skulle være tilfældet.
