### ISSUE TITLE
fskintra @ Heroku / AWS?

### ISSUE THREAD

**Issue by webjay** [svalgaard/fskintra#34]
# question
- Har nogen erfaring med at få fskintra til at køre på enten Heroku eller AWS ECS?
- Findes der en allerede kørende løsning man kan melde sig til?

p.s. Skønt at finde dette projekt, så jeg ikke selv skal kode det :)

**Comment by svalgaard** [comment]
Hej.

Manglende svar i knap en uges tid kunne tyde på at der ikke er andre der bruger det.
Det kunne dog helt sikkert være interessant at lave en guide til, hvordan man gør - det er jo ikke alle der har en lille server stående i et skab derhjemme. 😄 
Meld endeligt tilbage, hvis du får et op at køre og fik skrevet lidt om hvordan. Ellers kan det være at det sker i løbet af skoleåret.

**Comment by webjay** [comment]
Jeg har til at starte med puttet dit projekt ind i Docker:
https://github.com/webjay/fskintra/blob/master/docker.md#forældreintra-in-a-box

Næste mål er at få det til at køre på AWS ECS...
