### ISSUE TITLE
UNI-C login?

### ISSUE THREAD

**Issue by donkeylobster** [svalgaard/fskintra#37]
Jeg har fået at vide at fra næste skoleår vil det kun være muligt at logge på forældreintra med et UNI-C login. 

Nogen der ved om det kan lade sig gøre at logge ind automatisk med UNI login?

**Comment by svalgaard** [comment]
Unilogin burde fint kunne lade sig gøre, sålænge de ikke indfører en "captcha code" eller tilsvarende.

Pt har forældre (i det mindste på vores skole) ikke noget uni-login, men bruger et skolespecifikt login.

Har du evt. en URL hvor der står mere om dette?

**Comment by donkeylobster** [comment]
Har fået denne besked fra skolen 

>  Kære forældre. 
> 
> Fra sommerferien vil det kun være muligt at logge på Forældreintra med et UNI-login. Hvis I ikke har et UNI-login endnu, kan I få det ved at følge vedlagte vejledning. Når det er på plads, kan det bruges til såvel Forældreintra som Meebook - ét login til begge steder for alle jeres børn:-) 

På http://www.itslearning.dk/nu-kan-du-f-uni-login-til-forldreintra fremgår det at den enkelte skole kan vælge mellem almindelig, UNI-login eller begge.

**Comment by svalgaard** [comment]
OK. Det kunne godt ligne noget der bør kigges på - det vil dog nok kræve at ens skole bruger det, før man kan lave den tilsvarende kode. Jeg lægger det i bunken med ting vi burde kigge på en dag. :)

**Comment by svalgaard** [comment]
Lukkes. Er implementeret som en del af #38 .
